name: news_app
description: "News App with Clean Architecture"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Network
  dio: ^5.7.0

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Local Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # Functional Programming
  dartz: ^0.10.1

  # Navigation
  go_router: ^14.8.1

  # Google Fonts
  google_fonts: ^6.2.1

  # UI
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  image: ^4.3.0
  flutter_local_notifications: ^21.0.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
