// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSYucdcWUDofih_BI_SMccTHZTpKJ3taM',
    appId: '1:578159207410:android:87b6696e365dd8039bc16b',
    messagingSenderId: '578159207410',
    projectId: 'free-api-news',
    storageBucket: 'free-api-news.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS5hwQf4TeHEI1Sk0lfV0jkMeA4blSro4',
    appId: '1:578159207410:ios:2f9ff57572058ea39bc16b',
    messagingSenderId: '578159207410',
    projectId: 'free-api-news',
    storageBucket: 'free-api-news.firebasestorage.app',
    iosBundleId: 'com.nunu.newsApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5tdb3Hh5cuFhlQdsis1j0K9Lslwt3mJM',
    appId: '1:578159207410:web:a055bf43afaf1e8a9bc16b',
    messagingSenderId: '578159207410',
    projectId: 'free-api-news',
    authDomain: 'free-api-news.firebaseapp.com',
    storageBucket: 'free-api-news.firebasestorage.app',
    measurementId: 'G-2G5NKF429X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS5hwQf4TeHEI1Sk0lfV0jkMeA4blSro4',
    appId: '1:578159207410:ios:2f9ff57572058ea39bc16b',
    messagingSenderId: '578159207410',
    projectId: 'free-api-news',
    storageBucket: 'free-api-news.firebasestorage.app',
    iosBundleId: 'com.nunu.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5tdb3Hh5cuFhlQdsis1j0K9Lslwt3mJM',
    appId: '1:578159207410:web:dc5e216391aad9c79bc16b',
    messagingSenderId: '578159207410',
    projectId: 'free-api-news',
    authDomain: 'free-api-news.firebaseapp.com',
    storageBucket: 'free-api-news.firebasestorage.app',
    measurementId: 'G-51YWEYE07T',
  );

}